### ISSUE TITLE
NETStandard version

### ISSUE THREAD

**Issue by wonea** [giacomelli/HelperSharp#4]
Any plans for a NETStandard version?

**Comment by rsbueno** [comment]
I've created a pull request that solves it (#5).

**Comment by dhwed** [comment]
@giacomelli Can you please publish this new HelperSharp version that supports `netstandard2.0` on NuGet?

I'm needing to use https://github.com/giacomelli/SalesforceSharp in dotnet core and the first step is to get this dependency published.
